### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 3boodyxz** [VilotStar/LethalPosters#2]
There is no poster has been changed at all. I tried with a Thunderstore App and downloaded poster mods but it doesn't work. also, I have tried to open the files and add a "poster", and "tips" files to the path: "BepInEx\plugins\femboytv-LethalPosters", but it still doesn't work.

**Comment by Atakku** [comment]
it needs to be LethalPosters without `femboytv-`
the folder can be in `plugins\` or in a subfolder (mod/modpack) for example
`BepInEx\plugins\yourname-YourMod\LethalPosters\posters`
`BepInEx\plugins\yourname-YourMod\LethalPosters\tips`
also i think the mod will not work unless you have both of the folders at the moment

**Comment by 3boodyxz** [comment]
Thanks, it worked, I was having three issues: first, the file name was with the "femboytv-". second, one of the poster mods that is I didn't have a "posters" file.  Third, it was reloading 1 mod poster at a time.
I hope you can fix some of these issues and thank you for your fast response.

**Comment by nickolasjadams** [comment]
> i think the mod will not work unless you have both of the folders at the moment

Oh man! That's the thing that I needed to know! Thank you!
