### ISSUE TITLE
[FEATURE] JPEG Support?

### ISSUE THREAD

**Issue by aoqia194** [VilotStar/LethalPosters#3]
If there isn't already, could there be JPEG file support? Putting even a small amount of PNG files in a mod significantly increases the file size. For example, I have 150 PNG images in my mod but the file size is a ludicrous 500MB.

I was modifying your lpg Rust script to use JPEG but I wasn't even sure if the LethalPosters or LethalPaintings mods support JPEG files.

**Comment by Atakku** [comment]
it should already support it

**Comment by Atakku** [comment]
lpg uses png because thats the format the game assets were in afaik
you should also keep in mind that even if you compress the posters to jpg, it still wont affect the final vram usage

but im not sure if that should be a concern or not because im not sure how unity will allocate the vram in this specific case when we are swapping Texture2D objects

**Comment by aoqia194** [comment]
I am aware this comment is a bit late and this comment is not replying to the issue, but to provide information to anyone it concerns:
- JPEG has no transparency, therefore it will obviously not be transparent when the game converts it to PNG.
- JPEG compression is less jarring than PNG compression from my experience.
- Like above, if you have a full image that doesn't need transparency such as paintings that crop to fit and are >= the intended dimensions, it's best to use JPEG.
- When the game uses PNG, transparency makes it possible for the image to appear "smaller" in the game, though in reality the actual dimensions of the image are the same.

NOTES:
JPEG didn't really save that much space after the fact, as after some research about JPEG and PNG and how it works made me realise that you can get PNG files down to JPEG size with similar efforts; which is a win for us considering we want to keep the transparency channel (which takes up 1/4 of the bits of a PNG depending on the amount of pixels that are transparent).
I rewrote the [lpg](https://github.com/Atakku/lpg) tool from @Atakku to support PNG compression [here](https://github.com/aoqia194/lpg-python), but I haven't ironed out many of the bugs and there is still a lot to be improved for the cropping, considering it's trivial to find the "best" position to crop in a given image (example: faces cutting off).
